### ISSUE TITLE
Wrong package and plugin name in launch file

### ISSUE THREAD

**Issue by james-yoo** [auradar/au_4d_radar#1]
Hi, 

You should fix package and plugin name from :
https://github.com/auradar/au_4d_radar/blob/5219d10ce4fb22796cb6e38c38aac6358ff71a93/launch/run_radar.launch.py#L18-L19

to:
package='au_4d_radar',
plugin='au_4d_radar::device_au_radar_node',

**Comment by au-sensor1** [comment]
fixed.
